export const ATTACK_DEFINITIONS = [
    { id: '1', name: 'Stored XSS', description: 'Injects malicious script persistently into target database.', duration: 4000, baseSuccessProbability: 0.6, baseDetectionProbability: 0.4, impactLevel: 'Medium', resourceImpact: { cpu: 5, memory: 2 } },
    { id: '2', name: 'Reflected XSS', description: 'Injects script via crafted URL to target victims.', duration: 3000, baseSuccessProbability: 0.5, baseDetectionProbability: 0.5, impactLevel: 'Low', resourceImpact: { cpu: 3, memory: 1 } },
    { id: '3', name: 'CSRF', description: 'Forces user to execute unwanted actions on auth session.', duration: 3500, baseSuccessProbability: 0.5, baseDetectionProbability: 0.3, impactLevel: 'Medium', resourceImpact: { cpu: 2, memory: 1 } },
    { id: '4', name: 'Ransomware Simulation', description: 'Simulates encrypting filesystem and demanding ransom.', duration: 8000, baseSuccessProbability: 0.3, baseDetectionProbability: 0.8, impactLevel: 'Critical', resourceImpact: { cpu: 80, memory: 50, serviceStatus: 'degraded' } },
    { id: '5', name: 'Privilege Escalation', description: 'Attempts to gain root/admin access via misconfigurations.', duration: 6000, baseSuccessProbability: 0.4, baseDetectionProbability: 0.5, impactLevel: 'High', resourceImpact: { cpu: 15, memory: 10 } },
    { id: '6', name: 'Reverse Shell', description: 'Opens interactive shell connection back to attacker.', duration: 5000, baseSuccessProbability: 0.45, baseDetectionProbability: 0.7, impactLevel: 'Critical', resourceImpact: { cpu: 10, memory: 5 } },
    { id: '7', name: 'SYN Flood (DDoS)', description: 'Simulates massive volumetric TCP SYN attack.', duration: 10000, baseSuccessProbability: 0.8, baseDetectionProbability: 0.9, impactLevel: 'High', resourceImpact: { cpu: 95, memory: 30, serviceStatus: 'offline' } },
    { id: '8', name: 'Zero-Day Exploit', description: 'Randomized unknown vulnerability exploitation.', duration: 7000, baseSuccessProbability: 0.2, baseDetectionProbability: 0.1, impactLevel: 'Critical', resourceImpact: { cpu: 20, memory: 15 } },
    { id: '9', name: 'DNS Spoofing', description: 'Poisons DNS cache to redirect traffic.', duration: 4500, baseSuccessProbability: 0.5, baseDetectionProbability: 0.6, impactLevel: 'High', resourceImpact: { cpu: 5, memory: 5 } },
    { id: '10', name: 'Man-in-the-Middle', description: 'Intercepts traffic passing through the network.', duration: 6500, baseSuccessProbability: 0.4, baseDetectionProbability: 0.5, impactLevel: 'High', resourceImpact: { cpu: 15, memory: 8 } },
    { id: '11', name: 'Phishing Campaign', description: 'Sends deceptive emails to harvest credentials.', duration: 5000, baseSuccessProbability: 0.6, baseDetectionProbability: 0.2, impactLevel: 'Medium', resourceImpact: { cpu: 1, memory: 1 } },
    { id: '12', name: 'Malware Beaconing', description: 'Simulates C2 callbacks from compromised host.', duration: 10000, baseSuccessProbability: 0.7, baseDetectionProbability: 0.6, impactLevel: 'High', resourceImpact: { cpu: 2, memory: 2 } },
    { id: '13', name: 'Data Exfiltration', description: 'Steals sensitive data over encrypted channels.', duration: 9000, baseSuccessProbability: 0.5, baseDetectionProbability: 0.7, impactLevel: 'Critical', resourceImpact: { cpu: 25, memory: 40 } }
];
